/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CirculationRouteImport } from './routes/circulation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as MyBooksRouteImport } from './routes/my-books'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as CentersIndexRouteImport } from './routes/centers.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CirculationRoute = CirculationRouteImport.update({
  id: '/circulation',
  path: '/circulation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBooksRoute = MyBooksRouteImport.update({
  id: '/my-books',
  path: '/my-books',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentersIndexRoute = CentersIndexRouteImport.update({
  id: '/centers/',
  path: '/centers/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/circulation': typeof CirculationRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/inventory': typeof InventoryRoute
  '/my-books': typeof MyBooksRoute
  '/requests': typeof RequestsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/transfers': typeof TransfersRoute
  '/books/': typeof BooksIndexRoute
  '/centers/': typeof CentersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/circulation': typeof CirculationRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/inventory': typeof InventoryRoute
  '/my-books': typeof MyBooksRoute
  '/requests': typeof RequestsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/transfers': typeof TransfersRoute
  '/books': typeof BooksIndexRoute
  '/centers': typeof CentersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/circulation': typeof CirculationRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/inventory': typeof InventoryRoute
  '/my-books': typeof MyBooksRoute
  '/requests': typeof RequestsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/transfers': typeof TransfersRoute
  '/books/': typeof BooksIndexRoute
  '/centers/': typeof CentersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/circulation'
    | '/dashboard'
    | '/donations'
    | '/inventory'
    | '/my-books'
    | '/requests'
    | '/staff'
    | '/students'
    | '/transfers'
    | '/books/'
    | '/centers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/circulation'
    | '/dashboard'
    | '/donations'
    | '/inventory'
    | '/my-books'
    | '/requests'
    | '/staff'
    | '/students'
    | '/transfers'
    | '/books'
    | '/centers'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/circulation'
    | '/dashboard'
    | '/donations'
    | '/inventory'
    | '/my-books'
    | '/requests'
    | '/staff'
    | '/students'
    | '/transfers'
    | '/books/'
    | '/centers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CirculationRoute: typeof CirculationRoute
  DashboardRoute: typeof DashboardRoute
  DonationsRoute: typeof DonationsRoute
  InventoryRoute: typeof InventoryRoute
  MyBooksRoute: typeof MyBooksRoute
  RequestsRoute: typeof RequestsRoute
  StaffRoute: typeof StaffRoute
  StudentsRoute: typeof StudentsRoute
  TransfersRoute: typeof TransfersRoute
  BooksIndexRoute: typeof BooksIndexRoute
  CentersIndexRoute: typeof CentersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulation': {
      id: '/circulation'
      path: '/circulation'
      fullPath: '/circulation'
      preLoaderRoute: typeof CirculationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-books': {
      id: '/my-books'
      path: '/my-books'
      fullPath: '/my-books'
      preLoaderRoute: typeof MyBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centers/': {
      id: '/centers/'
      path: '/centers'
      fullPath: '/centers/'
      preLoaderRoute: typeof CentersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CirculationRoute: CirculationRoute,
  DashboardRoute: DashboardRoute,
  DonationsRoute: DonationsRoute,
  InventoryRoute: InventoryRoute,
  MyBooksRoute: MyBooksRoute,
  RequestsRoute: RequestsRoute,
  StaffRoute: StaffRoute,
  StudentsRoute: StudentsRoute,
  TransfersRoute: TransfersRoute,
  BooksIndexRoute: BooksIndexRoute,
  CentersIndexRoute: CentersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
