/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CentersRouteImport } from './routes/centers'
import { Route as CirculationRouteImport } from './routes/circulation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as MyBooksRouteImport } from './routes/my-books'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as CentersIndexRouteImport } from './routes/centers.index'
import { Route as CentersCenterIdRouteImport } from './routes/centers.$centerId'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as CentersCenterIdIndexRouteImport } from './routes/centers.$centerId.index'
import { Route as CentersCenterIdBooksBookIdRouteImport } from './routes/centers.$centerId.books.$bookId'
import { Route as CentersCenterIdStudentsStudentIdRouteImport } from './routes/centers.$centerId.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CentersRoute = CentersRouteImport.update({
  id: '/centers',
  path: '/centers',
  getParentRoute: () => rootRouteImport,
} as any)
const CirculationRoute = CirculationRouteImport.update({
  id: '/circulation',
  path: '/circulation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBooksRoute = MyBooksRouteImport.update({
  id: '/my-books',
  path: '/my-books',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)
const CentersIndexRoute = CentersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CentersRoute,
} as any)
const CentersCenterIdRoute = CentersCenterIdRouteImport.update({
  id: '/$centerId',
  path: '/$centerId',
  getParentRoute: () => CentersRoute,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentersCenterIdIndexRoute = CentersCenterIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CentersCenterIdRoute,
} as any)
const CentersCenterIdBooksBookIdRoute =
  CentersCenterIdBooksBookIdRouteImport.update({
    id: '/books/$bookId',
    path: '/books/$bookId',
    getParentRoute: () => CentersCenterIdRoute,
  } as any)
const CentersCenterIdStudentsStudentIdRoute =
  CentersCenterIdStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => CentersCenterIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRouteWithChildren
  '/centers': typeof CentersRouteWithChildren
  '/circulation': typeof CirculationRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/inventory': typeof InventoryRoute
  '/my-books': typeof MyBooksRoute
  '/requests': typeof RequestsRoute
  '/staff': typeof StaffRoute
  '/transfers': typeof TransfersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/centers/$centerId': typeof CentersCenterIdRouteWithChildren
  '/books/': typeof BooksIndexRoute
  '/centers/': typeof CentersIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/centers/$centerId/': typeof CentersCenterIdIndexRoute
  '/centers/$centerId/books/$bookId': typeof CentersCenterIdBooksBookIdRoute
  '/centers/$centerId/students/$studentId': typeof CentersCenterIdStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/circulation': typeof CirculationRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/inventory': typeof InventoryRoute
  '/my-books': typeof MyBooksRoute
  '/requests': typeof RequestsRoute
  '/staff': typeof StaffRoute
  '/transfers': typeof TransfersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books': typeof BooksIndexRoute
  '/centers': typeof CentersIndexRoute
  '/students': typeof StudentsIndexRoute
  '/centers/$centerId': typeof CentersCenterIdIndexRoute
  '/centers/$centerId/books/$bookId': typeof CentersCenterIdBooksBookIdRoute
  '/centers/$centerId/students/$studentId': typeof CentersCenterIdStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRouteWithChildren
  '/centers': typeof CentersRouteWithChildren
  '/circulation': typeof CirculationRoute
  '/dashboard': typeof DashboardRoute
  '/donations': typeof DonationsRoute
  '/inventory': typeof InventoryRoute
  '/my-books': typeof MyBooksRoute
  '/requests': typeof RequestsRoute
  '/staff': typeof StaffRoute
  '/transfers': typeof TransfersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/centers/$centerId': typeof CentersCenterIdRouteWithChildren
  '/books/': typeof BooksIndexRoute
  '/centers/': typeof CentersIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/centers/$centerId/': typeof CentersCenterIdIndexRoute
  '/centers/$centerId/books/$bookId': typeof CentersCenterIdBooksBookIdRoute
  '/centers/$centerId/students/$studentId': typeof CentersCenterIdStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/books'
    | '/centers'
    | '/circulation'
    | '/dashboard'
    | '/donations'
    | '/inventory'
    | '/my-books'
    | '/requests'
    | '/staff'
    | '/transfers'
    | '/books/$bookId'
    | '/centers/$centerId'
    | '/books/'
    | '/centers/'
    | '/students/'
    | '/centers/$centerId/'
    | '/centers/$centerId/books/$bookId'
    | '/centers/$centerId/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/circulation'
    | '/dashboard'
    | '/donations'
    | '/inventory'
    | '/my-books'
    | '/requests'
    | '/staff'
    | '/transfers'
    | '/books/$bookId'
    | '/books'
    | '/centers'
    | '/students'
    | '/centers/$centerId'
    | '/centers/$centerId/books/$bookId'
    | '/centers/$centerId/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/books'
    | '/centers'
    | '/circulation'
    | '/dashboard'
    | '/donations'
    | '/inventory'
    | '/my-books'
    | '/requests'
    | '/staff'
    | '/transfers'
    | '/books/$bookId'
    | '/centers/$centerId'
    | '/books/'
    | '/centers/'
    | '/students/'
    | '/centers/$centerId/'
    | '/centers/$centerId/books/$bookId'
    | '/centers/$centerId/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BooksRoute: typeof BooksRouteWithChildren
  CentersRoute: typeof CentersRouteWithChildren
  CirculationRoute: typeof CirculationRoute
  DashboardRoute: typeof DashboardRoute
  DonationsRoute: typeof DonationsRoute
  InventoryRoute: typeof InventoryRoute
  MyBooksRoute: typeof MyBooksRoute
  RequestsRoute: typeof RequestsRoute
  StaffRoute: typeof StaffRoute
  TransfersRoute: typeof TransfersRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centers': {
      id: '/centers'
      path: '/centers'
      fullPath: '/centers'
      preLoaderRoute: typeof CentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulation': {
      id: '/circulation'
      path: '/circulation'
      fullPath: '/circulation'
      preLoaderRoute: typeof CirculationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-books': {
      id: '/my-books'
      path: '/my-books'
      fullPath: '/my-books'
      preLoaderRoute: typeof MyBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
    '/centers/': {
      id: '/centers/'
      path: '/'
      fullPath: '/centers/'
      preLoaderRoute: typeof CentersIndexRouteImport
      parentRoute: typeof CentersRoute
    }
    '/centers/$centerId': {
      id: '/centers/$centerId'
      path: '/$centerId'
      fullPath: '/centers/$centerId'
      preLoaderRoute: typeof CentersCenterIdRouteImport
      parentRoute: typeof CentersRoute
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centers/$centerId/': {
      id: '/centers/$centerId/'
      path: '/'
      fullPath: '/centers/$centerId/'
      preLoaderRoute: typeof CentersCenterIdIndexRouteImport
      parentRoute: typeof CentersCenterIdRoute
    }
    '/centers/$centerId/books/$bookId': {
      id: '/centers/$centerId/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/centers/$centerId/books/$bookId'
      preLoaderRoute: typeof CentersCenterIdBooksBookIdRouteImport
      parentRoute: typeof CentersCenterIdRoute
    }
    '/centers/$centerId/students/$studentId': {
      id: '/centers/$centerId/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/centers/$centerId/students/$studentId'
      preLoaderRoute: typeof CentersCenterIdStudentsStudentIdRouteImport
      parentRoute: typeof CentersCenterIdRoute
    }
  }
}

interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface CentersCenterIdRouteChildren {
  CentersCenterIdIndexRoute: typeof CentersCenterIdIndexRoute
  CentersCenterIdBooksBookIdRoute: typeof CentersCenterIdBooksBookIdRoute
  CentersCenterIdStudentsStudentIdRoute: typeof CentersCenterIdStudentsStudentIdRoute
}

const CentersCenterIdRouteChildren: CentersCenterIdRouteChildren = {
  CentersCenterIdIndexRoute: CentersCenterIdIndexRoute,
  CentersCenterIdBooksBookIdRoute: CentersCenterIdBooksBookIdRoute,
  CentersCenterIdStudentsStudentIdRoute: CentersCenterIdStudentsStudentIdRoute,
}

const CentersCenterIdRouteWithChildren = CentersCenterIdRoute._addFileChildren(
  CentersCenterIdRouteChildren,
)

interface CentersRouteChildren {
  CentersCenterIdRoute: typeof CentersCenterIdRouteWithChildren
  CentersIndexRoute: typeof CentersIndexRoute
}

const CentersRouteChildren: CentersRouteChildren = {
  CentersCenterIdRoute: CentersCenterIdRouteWithChildren,
  CentersIndexRoute: CentersIndexRoute,
}

const CentersRouteWithChildren =
  CentersRoute._addFileChildren(CentersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BooksRoute: BooksRouteWithChildren,
  CentersRoute: CentersRouteWithChildren,
  CirculationRoute: CirculationRoute,
  DashboardRoute: DashboardRoute,
  DonationsRoute: DonationsRoute,
  InventoryRoute: InventoryRoute,
  MyBooksRoute: MyBooksRoute,
  RequestsRoute: RequestsRoute,
  StaffRoute: StaffRoute,
  TransfersRoute: TransfersRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
